default:
  image:
    name: docker/compose:latest
    entrypoint: ["/usr/bin/env"]
  before_script:
    - apk update
    - apk upgrade --available && sync
    - apk add git bash xmlstarlet
    - git submodule init
    - git submodule update
  tags:
    - sa111


tests:
  stage: test
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://dind:2375/
    DOCKER_DRIVER: overlay2
  script:
    - docker version
    - docker-compose version
    - bash scripts/test.sh
    - xmlstarlet ed -u "coverage/sources/source" -v "`pwd`/src" test_report/coverage_docker.xml > test_report/coverage.xml 
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: test_report/coverage.xml
      junit: test_report/junit.xml
      codequality: test_report/code_climate.json


code-quality:
  image: docker:stable
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://dind:2375/
    DOCKER_DRIVER: overlay2
  allow_failure: true
  before_script: []
  script:
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/ci-cd/codequality:latest" /code
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

