default:
  image:
    name: docker:latest
    entrypoint: ["/usr/bin/env"]

  before_script:
    - apk update
    - apk add docker-compose git
    - git submodule init
    - git submodule update
    - mkdir -p test_report

tests:
  stage: test
  script:
    - bash scripts/test.sh

  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: test_report/coverage.xml
      junit: test_report/junit.xml


code-quality:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  before_script: []
  script:
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/ci-cd/codequality:latest" /code
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

