apiVersion: v1
kind: Service
metadata:
  labels:
    name: adacs-job-controller
  name: adacs-job-controller
  namespace: jobcontroller
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: websocket
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    name: adacs-job-controller
  sessionAffinity: None
  type: ClusterIP
