---
# 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adacs-job-controller
  namespace: jobcontroller
  labels:
    name: adacs-job-controller
spec:
  replicas: 1
  selector:
    matchLabels:
        name: adacs-job-controller
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        name: adacs-job-controller
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: adacs-job-controller
          name: adacs-job-controller
          image: nexus.gwdc.org.au/docker/adacs_job_controller:0.54
          ports:
            - name: http
              containerPort: 8000
            - name: websocket
              containerPort: 8001
          resources: 
            requests:
              memory: "2048M"
              cpu: "2000m"
            limits:
              memory: "12288M"
              cpu: "4000m"
          tty: true
      imagePullSecrets:
      - name: regcred
... 
