apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: vault-agent
    app.kubernetes.io/instance: adacs-job-controller 
  name: secrets-integrator-adacs-job-controller
  namespace: jobcontroller
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      labels:
        app: vault-kube-integrator
    spec:
      backoffLimit: 1
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-init-first: 'true'
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/agent-inject-secret-job-server.yaml: kv/jobserver/adacs-job-controller
            vault.hashicorp.com/agent-inject-template-job-server.yaml: |
              {{- with secret "kv/jobserver/adacs-job-controller" -}}
              apiVersion: v1
              kind: Secret
              type: Opaque
              stringData:
                {{ range $k, $v := .Data }}
                {{ $k }}: "{{ $v }}"
                {{ end }}
              metadata:
                namespace: jobcontroller
                name: adacs-job-controller
              {{- end }}
            vault.hashicorp.com/agent-pre-populate-only: 'true'
            vault.hashicorp.com/role: adacs-job-controller 
        spec:
          containers:
            - command:
                - kubectl
                - apply
                - '-f'
                - /vault/secrets/
              image: 'bitnami/kubectl:1.17.4'
              imagePullPolicy: IfNotPresent
              name: adacs-job-controller-vault-kube-integrator
              resources: {}
          imagePullSecrets:
            - name: regcred
          restartPolicy: Never
          serviceAccountName: adacs-job-controller
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 1
