---
# 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gwcloud-job-server
  namespace: gwcloud
  labels:
    name: gwcloud-job-server
spec:
  replicas: 1
  selector:
    matchLabels:
        name: gwcloud-job-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        name: gwcloud-job-server
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: gwcloud-auth
            - secretRef:
                name: common
          name: gwcloud-job-server
          image: nexus.gw-cloud.org/gwcloud-dev/gwcloud_job_server:0.16
          ports:
            - name: http
              containerPort: 8000
            - name: websocket
              containerPort: 8001
          resources: {}
          tty: true
        imagePullSecrets:
        - name: regcred
... 
