---
# 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gwcloud-job-server
  namespace: gwcloud
  labels:
    name: gwcloud-job-server
spec:
  replicas: 1
  selector:
    matchLabels:
        name: gwcloud-job-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        name: gwcloud-job-server
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: job-server
            - secretRef:
                name: common
          name: gwcloud-job-server
          image: nexus.gwdc.org.au/docker/gwcloud_job_server:0.36
          ports:
            - name: http
              containerPort: 8000
            - name: websocket
              containerPort: 8001
          resources: 
            requests:
              memory: "2048M"
              cpu: "2000m"
            limits:
              memory: "12288M"
              cpu: "4000m"
          tty: true
      imagePullSecrets:
      - name: regcred
... 
