apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: jobserver
  name: jobserver
  namespace: gwcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
      volume: jobserver
  volumeMode: Filesystem
  volumeName: jobserver
