apiVersion: v1
kind: Service
metadata:
  labels:
    name: gwcloud-job-server
  name: gwcloud-job-server
  namespace: gwcloud
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  - port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    name: gwcloud-job-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}