resources:
  # - secret.yaml # implies secret has been predeployed
  - gwcloud_job_server_db_deployment.yaml
  - gwcloud_job_server_db_service.yaml
  - gwcloud_job_server_deployment.yaml
  - gwcloud_job_server_service.yaml
