# Generated by Django 3.0.4 on 2020-03-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobserver', '0002_auto_20200309_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='bundle',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='cluster',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
