# Generated by Django 3.0.4 on 2020-03-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobserver', '0004_job_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='sent',
        ),
    ]
