# Generated by Django 3.0.4 on 2020-03-11 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobserver', '0005_remove_job_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedownload',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobserver.Job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filedownload',
            name='path',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
