version: '3.4'

services:
  web:
    build:
      dockerfile: ./docker/adacs_job_controller.Dockerfile
      context: ..
      target: production
    container_name: adacs_job_controller
    env_file: ../.env
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ../config:/app/config:ro
      - ./logs:/jobserver/logs
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:5.7
    container_name: adacs_job_controller_mysql
    env_file: ../.env
    volumes:
      - ./db:/var/lib/mysql
    restart: unless-stopped
