version: '3.4'

services:
  web:
    build:
      dockerfile: ./docker/adacs_job_controller.Dockerfile
      context: ..
      target: test
    image: adacs_job_controller_test 
    container_name: adacs_job_controller_test
    volumes:
      - ../test_report:/test_report
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: adacs_job_controller_mysql_test
    volumes: 
      - var_lib_mysql_adacs_job_controller_test:/var/lib/mysql

volumes:
  var_lib_mysql_adacs_job_controller_test:

