version: '3'

services:
  web:
    build:
      dockerfile: ./docker/adacs_job_controller.Dockerfile
      context: ..
      target: test
    container_name: adacs_job_controller_valgrind
    env_file: ../.env
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: adacs_job_controller_mysql_valgrind
    env_file: ../.env
    volumes:
      - var_lib_mysql_adacs_jobcontroller_valgrind:/var/lib/mysql

volumes:
  var_lib_mysql_adacs_jobcontroller_valgrind:
