version: '3.4'

services:
  web:
    build:
      dockerfile: ./docker/adacs_job_controller.Dockerfile
      context: ..
      target: test
    image: adacs_job_controller_valgrind 
    container_name: adacs_job_controller_valgrind
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: adacs_job_controller_mysql_valgrind
    volumes: 
      - var_lib_mysql_adacs_jobcontroller_valgrind:/var/lib/mysql

volumes:
  var_lib_mysql_adacs_job_controller_valgrind:

