# Generated by Django 3.0.4 on 2020-04-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobserver', '0008_auto_20200311_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='bundle',
            field=models.CharField(max_length=40),
        ),
    ]
