# Generated by Django 3.0.4 on 2020-04-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobserver', '0009_auto_20200408_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobhistory',
            name='what',
            field=models.CharField(default='system', max_length=128),
            preserve_default=False,
        ),
    ]
