# Generated by Django 3.0.4 on 2020-05-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobserver', '0011_clusteruuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusteruuid',
            name='cluster',
            field=models.CharField(max_length=200),
        ),
    ]
