# Generated by Django 3.0.4 on 2020-10-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobserver', '0014_auto_20200518_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application',
            field=models.CharField(default='bilby', max_length=32),
            preserve_default=False,
        ),
    ]
