# Generated by Django 3.2.2 on 2021-07-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobserver', '0017_filelistcache'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filelistcache',
            old_name='fileSize',
            new_name='file_size',
        ),
        migrations.AlterField(
            model_name='filelistcache',
            name='path',
            field=models.CharField(db_index=True, max_length=765),
        ),
        migrations.AlterUniqueTogether(
            name='filelistcache',
            unique_together={('job', 'path')},
        ),
    ]
