# Generated by Django 3.2.14 on 2022-07-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobserver', '0018_auto_20210706_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedownload',
            name='bundle',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filedownload',
            name='cluster',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filedownload',
            name='job',
            field=models.IntegerField(),
        ),
    ]
