# Generated by Django 3.2.14 on 2022-10-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobserver', '0022_clusterjob_clusterjobstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.CharField(db_index=True, max_length=200)),
                ('bundle_hash', models.CharField(db_index=True, max_length=40)),
                ('content', models.TextField()),
            ],
        ),
    ]
