# Generated by Django 3.0.4 on 2020-03-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobserver', '0003_auto_20200310_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='sent',
            field=models.BooleanField(default=True),
        ),
    ]
