# Generated by Django 3.0.4 on 2020-05-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobserver', '0013_migrate_job_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhistory',
            name='what',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
